const MAIN = {
  SET : 'MAIN_SET',
}
const JOURNAL = {
  SEND    : 'JOURNAL_SEND',
  FETCH   : {
    _    : 'JOURNAL_FETCH',
    MORE : 'JOURNAL_FETCH_MORE',
  },
  REPLACE : {
    _ : 'JOURNAL_REPLACE',
  },
  ADD     : {
    TOP    : 'JOURNAL_ADD_TOP',
    BOTTOM : 'JOURNAL_ADD_BOTTOM',
  },
  UPDATE  : {
    INPUT : 'JOURNAL_UPDATE_INPUT',
  },
  STATUS  : {
    SUCCESS : 'JOURNAL_STATUS_SUCCESS',
    REQUEST : 'JOURNAL_STATUS_REQUEST',
    FAILED  : 'JOURNAL_STATUS_FAILED',
  },
}
const ACCOUNT = {
  SEND    : 'ACCOUNT_SEND',
  REMOVE  : 'ACCOUNT_REMOVE',
  FETCH   : {
    _    : 'ACCOUNT_FETCH',
    LIST : 'ACCOUNT_FETCH_LIST',
  },
  REPLACE : {
    _    : 'ACCOUNT_REPLACE',
    LIST : 'ACCOUNT_REPLACE_LIST',
  },
  STATUS  : {
    SUCCESS : 'ACCOUNT_STATUS_SUCCESS',
    REQUEST : 'ACCOUNT_STATUS_REQUEST',
    FAILED  : 'ACCOUNT_STATUS_FAILED',
  },
}

const COMPANY = {
  FETCH   : 'COMPANY_FETCH',
  SEND    : 'COMPANY_SEND',
  REPLACE : 'COMPANY_REPLACE',
  ADD     : 'COMPANY_ADD',
  STATUS  : {
    SUCCESS : 'COMPANY_STATUS_SUCCESS',
    REQUEST : 'COMPANY_STATUS_REQUEST',
    FAILED  : 'COMPANY_STATUS_FAILED',
  },
}

export { MAIN, JOURNAL, ACCOUNT, COMPANY }
