const COA = {
	FETCH: 'COA_FETCH',
	SAVE: 'COA_SAVE',
	NEW: 'COA_NEW',
	NEW_SAVE: 'COA_NEW_SAVE',
}

const LEDGER = {
	FETCH: 'LEDGER_FETCH',
	SAVE: 'LEDGER_SAVE',
	NEW: 'LEDGER_NEW',
	NEW_SAVE: 'LEDGER_NEW_SAVE',
}

const JOURNAL = {
	FETCH: 'JOURNAL_FETCH',
	SAVE: 'JOURNAL_SAVE',
	NEW: 'JOURNAL_NEW',
	NEW_SAVE: 'JOURNAL_NEW_SAVE',
}

export { COA, LEDGER, JOURNAL }
