// const CATAGORY = {
//   FETCH: 'CATAGORY_FETCH',
//   SAVE: 'CATAGORY_SAVE',
// }
// const ACCOUNT = {
//   FETCH: 'ACCOUNT_FETCH',
//   SAVE: 'ACCOUNT_SAVE',
//   ADD: 'ACCOUNT_ADD',
//   CHANGE: 'ACCOUNT_CHANGE',
// }

// const LEDGER = {
//   FETCH: 'LEDGER_FETCH',
//   SAVE: 'LEDGER_SAVE',
// }

const JOURNAL = {
  FETCH: 'JOURNAL_FETCH',
  SAVE: 'JOURNAL_SAVE',
  NEW: 'JOURNAL_NEW',
  NEW_SAVE: 'JOURNAL_NEW_SAVE',
}

export { JOURNAL }
