// const CATAGORY = {
//   FETCH: 'CATAGORY_FETCH',
//   SAVE: 'CATAGORY_SAVE',
// }
// const ACCOUNT = {
//   FETCH: 'ACCOUNT_FETCH',
//   SAVE: 'ACCOUNT_SAVE',
//   ADD: 'ACCOUNT_ADD',
//   CHANGE: 'ACCOUNT_CHANGE',
// }

// const LEDGER = {
//   FETCH: 'LEDGER_FETCH',
//   SAVE: 'LEDGER_SAVE',
// }

const JOURNAL = {
  FETCH: {
    INIT: 'JOURNAL_FETCH_INIT',
    MORE: 'JOURNAL_FETCH_MORE',
    ACCOUNT: 'JOURNAL_FETCH_ACCOUNT',
  },
  SAVE: {
    INIT: 'JOURNAL_SAVE_INIT',
    MORE: 'JOURNAL_SAVE_MORE',
    ACCOUNT: 'JOURNAL_SAVE_ACCOUNT',
  },
}

export { JOURNAL }
